### ISSUE TITLE
Allow the use of PDC with CD4PE

### ISSUE THREAD

**Issue by zigsphere** [betadots/pdc#27]
We would love to use the PDC container with CD4PE; however, it seems that PDC doesn't work out of the box like the puppet/puppet-dev-tools:4.x container that comes standard with the CD4PE installation. I'm not sure if code needs to be mounted in a different directory in PDC in order to run pdk validations, unit tests, etc against our Puppet code. We would love to support this now that Puppet 8 is supported.

**Comment by rwaffen** [comment]
can you describe more in detail what your needs are? Maybe then we can help more or change some behavior of the container.
We built this container in the first place to have a replacement for puppet/puppet-dev-tools with newer software.

**Comment by zigsphere** [comment]
When using puppet/puppet-dev-tools in CD4PE, it runs as is when specifying this container in the docker image name field. Perhaps there is a default workdir in this container.

In the pdc container, using the container without arguments results in:

```
2023-12-21 22:18:30 UTC: Message: pdk (INFO): Unit tests can only be run from inside a valid module directory.
```

Maybe it's /repo as the default location in puppet/puppet-dev-tools? Trying to understand where to mount if something needs to be changed.

**Comment by zigsphere** [comment]
I got it working. So CD4PE expects /repo to be in the container since /repo is the WORKDIR in puppet/puppet-dev-tools. By setting `-w "/repo"` and an argument in CD4PE fixes this issue.

Thanks

**Comment by rwaffen** [comment]
i closing this issue, if there is still something to be discussed please re-popen.
