### ISSUE TITLE
Replacement for Vox Pupuli testing Container?

### ISSUE THREAD

**Issue by bastelfreak** [betadots/pdc#49]
In the past, Vox Pupuli distributed a Dockerfile: https://github.com/voxpupuli/modulesync_config/pull/827/files
It wasn't properly maintained. But it adds a certain entry bar for new contributors if they've to deal with a (modern) local Ruby version. I think it would be great if we had a Dockerfile again and people can switch between container/non-container local testing and I think the pdc could provide this.

**Comment by rwaffen** [comment]
we will pursue this further with https://github.com/voxpupuli/container-voxbox
